# Generated by Django 4.2.8 on 2025-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_doppelt_abgehen',
            field=models.BooleanField(default=False),
        ),
    ]
